name: Deploy Cloudflare Workers

inputs:
  working-directory:
    required: true
    type: string

  account-id:
    required: true
    type: string

  api-token:
    required: true
    type: string

  environment:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@main
      with:
        node-version-file: ".nvmrc"

    - name: Cache Dependencies
      id: cache
      uses: actions/cache@main
      with:
        key: ${{ hashFiles(format('{0}/{1}', inputs.working-directory, 'package-lock.json')) }}
        path: ${{ format('{0}/{1}', inputs.working-directory, 'node_modules') }}

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
      working-directory: ${{ inputs.working-directory }}

    - name: Deploy to Cloudflare Workers
      uses: cloudflare/wrangler-action@v3
      with:
        accountId: ${{ inputs.account-id }}
        apiToken: ${{ inputs.api-token }}
        workingDirectory: ${{ inputs.working-directory }}
        command: deploy --env ${{ inputs.environment }}
